name: Deploy to OVH FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cluster011.hosting.ovh.net
          username: orkidees-03
          password: ${{ secrets.orkidees_03 }}
          port: 21
          local-dir: ./
          server-dir: ./www/IF08/cheesecake/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md